name: ists_eventos
description: Aplicación de gestión de eventos con QR para ISTS Loja
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  mobile_scanner: ^3.5.6  
  qr_flutter: ^4.1.0
  path_provider: ^2.1.1
  path: ^1.8.3
  share_plus: ^7.2.1
  image_gallery_saver: ^2.0.3
  permission_handler: ^11.0.1
  flutter_local_notifications: ^16.2.0
  sqflite_common_ffi: ^2.3.0
  intl: ^0.18.1
  url_launcher: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/